#!/usr/bin/env python3
# -*- coding: latin-1 -*-

from configuration import Configuration

def main( argv ):
    

if __name__ == "__main__":
    main([]) if len( sys.argv ) == 0 else main( sys.argv[ 1: ])